bower.json
components/d2l-organization-info/d2l-organization-info.html
components/d2l-organization-info/localize-behavior.html
demo/d2l-organization-info.html
demo/data/organization-current.json
demo/data/organization-future.json
demo/data/organization-past.json
test/d2l-organization-info/d2l-organization-info.html
test/d2l-organization-info/d2l-organization-info.js

This isn't the fully-correct implementation, as that will involve adding the status badge between the header and content. However, this is a first pass, which moves the future/ended/inactive status of the organization into the `d2l-organization-info` component. This displays the same information that was previously displayed in the image overlay in the `d2l-enrollment-card`, meaning that can now be removed.

US97555 Add future/ended/inactive support

---

components/d2l-organization-info/d2l-organization-info.html

The course code would show up on the same line as the course title. It no longer does this.
I have a branch where I am splitting up `d2l-organization-info` However, that will take a little longer. So this is the fix for the current layout.

made d2l-card-content-meta a block instead inline-block.

---

all-imports.html
components/d2l-organization-behavior.html
components/d2l-organization-date/d2l-organization-date.html
components/d2l-organization-date/localize-behavior.html
components/d2l-organization-info/d2l-organization-info.html
components/d2l-organization-name/d2l-organization-name.html
d2l-organization-date.html
d2l-organization-name.html
demo/d2l-organization-date/d2l-organization-date-demo.html
demo/d2l-organization-info/d2l-organization-info-demo.html
demo/d2l-organization-name/d2l-organization-name-demo.html
demo/data/organization-current.json
demo/data/organization-future.json
demo/data/organization-past.json
demo/data/presentation/1.json
demo/data/presentation/2.json
demo/data/presentation/3.json
index.html
test/d2l-organization-date/d2l-organization-date.html
test/d2l-organization-date/d2l-organization-date.js
test/d2l-organization-info/d2l-organization-info.js
test/d2l-organization-name/d2l-organization-name.html
test/d2l-organization-name/d2l-organization-name.js
test/d2l-organization-updates/d2l-organization-updates.js
test/index.html

Split d2l-organization-date into its own component.
Split d2l-organization-name into its own component.
d2l-organization-info no longer has the above information.
d2l-organization-info offers info such as course code and semester name.
Added demos for each of the components.

Split d2l-organization into smaller components.

---

components/d2l-organization-consortium/d2l-organization-consortium-tabs.js
components/d2l-organization-date/d2l-organization-date.js
components/d2l-organization-detail-card/d2l-organization-detail-card.js
components/d2l-organization-image/d2l-organization-image.js
components/d2l-organization-info/d2l-organization-info.js
components/d2l-organization-name/d2l-organization-name.js
components/d2l-organization-updates/d2l-organization-updates.js
package.json

This simply moves the observers below the properties to fix the sort linting.

Adjust order to fix sort linting.

---

components/d2l-organization-consortium/d2l-organization-consortium-tabs.js

This shouldn't have been added to a main component, it only belongs in tests and demo pages

remove whitelist from constorium tabs component

---

components/d2l-organization-consortium/d2l-organization-consortium-tabs.js
test/d2l-organization-consortium/d2l-organization-consortium-tabs.js

This change allows the component to be configured externally allowing us to let the lms control when to render out the tabs.
The default of 2 was picked as that seems to be the most likely scenario required.

add render threshold (d2l-organization-consortium-tabs)

---

components/d2l-organization-detail-card/d2l-organization-detail-card.js

[Port of this PR on the `d2l-enrollment-detail-card` to the `d2l-organization-detail-card`](https://github.com/BrightspaceHypermediaComponents/enrollments/pull/136)
This pull request updates the `d2l-organization-detail-card` to show pulse every 1.8 seconds instead of shimmering. The animation now also applies to the text placeholders instead of just the image placeholder.

Change the d2l-organization-detail-card skeleton to use a pulse animation

---

components/d2l-organization-detail-card/d2l-organization-detail-card.js
demo/d2l-organization-detail-card/d2l-organization-detail-card-demo.html
test/d2l-organization-detail-card/d2l-organization-detail-card.js

1. Events
-  A `d2l-organization-detail-card-image-loaded` event is fired when the card image loads.
- A `d2l-organization-detail-card-text-loaded` event is fired when the card text loads.
2. A reveal timeout was added to show the image and text after 2 seconds even if the `--d2l-organization-detail-card-loading` style has been applied to force the card to show its content even if the entire page doesn't load successfully.

Add d2l-organization-detail-card loading states

---

components/d2l-organization-detail-card/d2l-organization-detail-card.js
test/d2l-organization-detail-card/d2l-organization-detail-card.js

1. Add href to loaded events to be able to determine which `d2l-organization-detail-card` fired the event.
1. Add stop-gap solution to delay loaded event firing until the module sequences have loaded until we can get the sequence count from the siren-sdk.

Add href to loaded events and stop-gap timeout before firing loaded events

---

components/d2l-organization-updates/OrganizationUpdatesMixin.js
components/d2l-organization-updates/d2l-organization-updates.js
package.json

This is just a temporary change.
Background: we don't want to support `iron-iconset-svg`s with the Lit version of icon. I will be adding support to Lit icon for custom SVGs like this place is using, but it will first have to upgrade to Lit and then switch over.
I'm also going to reach out to Bob/Sarah separately and see if using a custom icon is even necessary here.

using iron-icon instead of d2l-icon with iron-iconset-svg

---

components/d2l-organization-consortium/d2l-organization-consortium-tabs.js
demo/d2l-organization-consortium/d2l-organization-consortium.html

- Remove `overflow: hidden` to prepare for the scrollbar work
- Small design adjustments requested by Jeff, we're making the tabs a bit bigger
- Use `d2l-navigation-band` in the demo

US109311 - Design Tweaks

---

components/d2l-organization-consortium/d2l-organization-consortium-tabs.js
test/d2l-organization-consortium/d2l-organization-consortium-tabs.js
test/d2l-organization-consortium/data.js

When in the mobile view, the org tabs go inside the mobile menu.  We want to add a notification dot to the hamburger button if any of the org tabs have notifications.
If at least one of the org tabs has a notification, the `d2l-organization-consortium-tabs-notification-update` event will be fired.  If something changes after the cache update or during the poll for new notifications (going from no notifications to some, or going from some to none), additional events will be sent.  This goes along with a PR in the LE to listen for this event and add/remove the notification dot as needed.
This will be added to 20.19.11 and master.

US110536 - Add notification update event for the org tabs

---

components/d2l-organization-availability-set/.eslintrc.json
components/d2l-organization-availability-set/README.MD
components/d2l-organization-availability-set/d2l-current-organization-availability.js
components/d2l-organization-availability-set/d2l-organization-availability-set.js
components/d2l-organization-availability-set/d2l-organization-availability.js
components/d2l-organization-availability-set/lang/en.json
components/d2l-organization-availability-set/localization.js
demo/d2l-organization-availability-set/d2l-organization-availability-set.html
demo/data/organization-availability-set/orgUnitAvailabilityCurrent.json
demo/data/organization-availability-set/orgUnitAvailabilityExplicit.json
demo/data/organization-availability-set/orgUnitAvailabilityInheritWithType.json
demo/data/organization-availability-set/organization-availability-set.json
demo/data/organization-availability-set/organization121147.json
demo/data/organization-availability-set/organization6606.json
demo/data/organization-availability-set/organization6609.json
demo/index.html
organizations.serge.json
package.json
test/d2l-organization-availability-set/d2l-current-organization-availability.html
test/d2l-organization-availability-set/d2l-current-organization-availability.js
test/d2l-organization-availability-set/d2l-organization-availability-set.js
test/d2l-organization-availability-set/d2l-organization-availability.html
test/d2l-organization-availability-set/d2l-organization-availability.js
test/d2l-organization-availability-set/data.js
test/index.html

Uses siren-sdk changes here: https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/79
- calls availabilitySetCollection API and cache-primer
- renders availability set list with properly formatted type description (e.g. The Course Offering xyz, The Department xyz, Every Program under the Department xyz, Every Org Unit under the Course Template xyz)
- renders "Current Org Unit: xyz" with checkbox in correct checked/unchecked state and with correct enabled/disabled state based on siren actions.
- show/hide "Add Org Units" button when appropriate

Render default Organization Availability Set

---

components/d2l-organization-consortium/d2l-organization-consortium-tabs.js
test/d2l-organization-consortium/d2l-organization-consortium-tabs.js

This is in response to an issue Minnstate had when testing.  After they clear the notification from the navbar, it won't go away in the org tab until we poll again (up to five minutes later), they refresh the page, or they navigate to a new page.
Instead of hooking up an event system to tell the tabs to re-poll early, we decided to remove the notification dot on the selected tab altogether.  You also won't see a notification dot on the hamburger icon of the mobile menu if the tab you are on is the only one with a notification

US111920 - Remove notification dot from selected tab

---

components/d2l-organization-availability-set/d2l-current-organization-availability.js
components/d2l-organization-availability-set/d2l-organization-availability.js
test/d2l-organization-availability-set/d2l-organization-availability.js

Some timing issue. What happens in the function trying to localize our item descriptions is called before the `shouldUpdate` method in the localize-mixin happens, which is where the language resources are loaded. So we end up trying to localize and it sees no language files and fails silently.

Fix trying to localize before localization resources are loaded

---

components/d2l-organization-consortium/d2l-organization-consortium-tabs.js

So after investigating, the polyfill for `focus-visible` seems a bit scary perf-wise, a trimmed-down org-tabs specific polyfill was seen as undesirable, and the current implementation of `:-moz-focusring` is buggy.
I found another suggestion that actually works out super nicely for our use-case, and wanted to put it up to see if anyone can think of unwanted side effects.  What I'm doing is adding `tabindex="-1"` to the inner element inside the link.  This causes a click to focus on that element and use its focus styles (none), whereas a tab focuses on the outer `a` element (where the focus styles live).  This works perfectly on Chrome, Edge and Firefox, and I tested all three with NVDA and it doesn't interpret this any differently from what I can tell.  Would be good to test on VoiceOver …

US111492 - Remove focus styles when clicking a tab

---

components/d2l-organization-admin-list/d2l-organization-admin-list-pager.js
components/d2l-organization-admin-list/d2l-organization-admin-list-search-header.js
components/d2l-organization-admin-list/d2l-organization-admin-list.js
components/d2l-organization-admin-list/lang/en.js
components/d2l-organization-admin-list/localization.js
demo/d2l-organization-admin-list/d2l-organization-admin-list.html
demo/data/organization-collection/organization-activity-usage.json
demo/data/organization-collection/organization-collection-1.json
demo/data/organization-collection/organization-collection-2.json
package.json
test/d2l-organization-admin-list/d2l-organization-admin-list.html
test/d2l-organization-admin-list/d2l-organization-admin-list.js
test/index.html
wct.conf.json

This pull request adds a component to list all org units through the organizations HM domain with support for paging, searching, and creating new org units.

Add the d2l-organization-admin-list component

---

components/d2l-organization-detail-card/d2l-organization-detail-card.js

https://rally1.rallydev.com/#/39602890252d/detail/defect/361158170068?fdp=true
Start/End dates are displayed in the activity list without any emphasis that distinguishes it from the activity description.
Discussed with Abbie. A space(24px) is added between date and description

added 24px space between date and description

---

components/d2l-organization-admin-list/d2l-organization-admin-list-pager.js

[DE37563](https://rally1.rallydev.com/#/detail/defect/363231455104?fdp=true)
A user was able to enter any number into the "goto page" input area, resulting in requests for negative numbers, floats, numbers greater than the total page number, and numbers with "e" in them. A short validation check has been added to the pager to prevent all of these cases. The pager will reset its input to the current page on bad input, which is currently how Discussions handles this case.

Fixed infinite loading defect in admin pager

---

components/d2l-organization-admin-list/d2l-organization-admin-list.js
components/d2l-organization-admin-list/lang/en.js

[DE37492](https://rally1.rallydev.com/#/detail/defect/362512928744?fdp=true)
Aria text added to delete button. Text while reading with a screen reader matches the label for deleting activities and includes title: "Remove learning path, {name}. Button"

Delete learning path button is now accessible

---

components/d2l-organization-admin-list/d2l-organization-admin-list.js
components/d2l-organization-admin-list/lang/en.js

[DE37552](https://rally1.rallydev.com/#/detail/defect/363051082516?fdp=true)
Changed language in toast to "{LP name} was removed successfully."

Changed lang to include the deleted org's name and specified text

---

components/d2l-organization-admin-list/d2l-organization-admin-list.js

This pr resolves a defect where loading any item in the admin list twice or more will cause an error and prevent refreshing the page on deletion.
This error can be caused by searching and then deleting something on the first page (Initial load -> second load via search). It can also be caused by going to the first page, second page, back to the first page, and then deleting (initial load p1 -> initial load p2 -> second load p1).
These changes resolve the defect by disposing the items and collection entities before their references are lost to those of the search or the page change. This prevents them from posthumously firing the events that would throw an error.

DE37585 dispose when loading new entities

---

components/d2l-organization-admin-list/d2l-organization-admin-list.js
components/d2l-organization-admin-list/lang/en.js

[DE37521](https://rally1.rallydev.com/#/detail/defect/362781454568?fdp=true)
The added visibility status takes advantage of the list component's secondary slot, which is meant exactly for this sort of thing.

Added visibility status to admin list page

---

components/d2l-organization-admin-list/d2l-organization-admin-list.js

This PR will resolve the loading black boxes in Edge, setting them to animate and pulse like in other browsers.
In Edge pre-Credge, if: 
- A css animation contains a css var, and 
- the animation is played in an SVG shape like a rect, 
Then there must also be a `fill:` css property applied to the SVG rect, and the fill colour must be assigned by a css variable, though the chosen variable doesn't seem to matter.
Using a basic color will block the animation, but using no fill property at all will render as a black box.

Added background fill to skeletons to fix Edge

---

components/d2l-organization-consortium/d2l-organization-consortium-tabs.js

This is not needed and is causing a console warning.

Remove include from style tag

---

components/d2l-organization-admin-list/d2l-organization-admin-list.js
components/d2l-organization-admin-list/lang/ar.js
components/d2l-organization-admin-list/lang/de.js
components/d2l-organization-admin-list/lang/en.js
components/d2l-organization-admin-list/lang/es.js
components/d2l-organization-admin-list/lang/fr.js
components/d2l-organization-admin-list/lang/ja.js
components/d2l-organization-admin-list/lang/ko.js
components/d2l-organization-admin-list/lang/nl.js
components/d2l-organization-admin-list/lang/pt.js
components/d2l-organization-admin-list/lang/sv.js
components/d2l-organization-admin-list/lang/tr.js
components/d2l-organization-admin-list/lang/zh-tw.js
components/d2l-organization-admin-list/lang/zh.js

**Context**
[DE38052](https://rally1.rallydev.com/#/detail/defect/372792424408?fdp=true)
This changes the trashcan delete button to a context menu that includes any actions for the learning path list item in the admin list page. A new property called `actions` has been created to house all action handlers; this makes room for expansion of this menu later.
The context menu is based off of a similar menu found in the My Courses widget and leverages `@brightspace-ui/core/dropdown/dropdown-more`.
**Quality**
* Tested with demo page
* Tested with local instance of BSI

Update delete button to context menu

---

components/d2l-organization-detail-card/d2l-organization-detail-card.js

**Context**
[DE37652](https://rally1.rallydev.com/#/detail/defect/365729624044?fdp=true)
A similar change was pushed to the `enrollments` components. Makes inactive courses or those without a 'has-link' attribute appear greyed out.
**Quality**
* Tested with demo page
* Tested with a local instance of BSI
* Tested with a local LE instance

Adding styles to prevent inactive courses from appearing clickable

---

components/d2l-organization-image/d2l-organization-image.js

Problem to be fixed:
When Learning Path organization unit is deleted in Learning Paths admin page, the _onOrganizationChange handler in d2l-organization-image is throwing exception.

handle null organization in d2l-organization-image _onOrganizationChange

---

components/d2l-organization-detail-card/d2l-organization-detail-card.js

While using Voiceover + Safari, course links are read out as "Course 3, text element". These should be read out as links instead to avoid confusion.
[DE37662](https://rally1.rallydev.com/#/357252966636d/detail/defect/366052133056?fdp=true)

added title for link and hide text for voice over

---

components/d2l-organization-detail-card/d2l-organization-detail-card.js

[DE37645](https://rally1.rallydev.com/#/357252966636d/custom/367300408400?qdp=%2Fdetail%2Fdefect%2F365681597704)
If you shrink the browser window horizontally to its smallest breakpoint, the module completion circles will end up being cut off.  
Before
After

add right padding so circle meter wont cut off

---

components/d2l-organization-date/d2l-organization-date.js
test/d2l-organization-date/d2l-organization-date.js

Related to https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/184, I'm migrating usages of the `processedDate` function from `OrganizationEntity` to no longer access `beforeStartDate` and `afterEndDate` directly, and to instead use the new functions.  In this case however, it's only used in sending an event that is not consumed by anything.  So just removing the event here.
I expect this was used before moving to the `siren-sdk`, which allows consumers of this component to get the info easily themselves instead of through this event.

DE38903 - Remove unused event and its tests from d2l-organization-date

---

components/d2l-organization-updates/build/lang/en.js
components/d2l-organization-updates/lang/en.json

This brings the my courses widget in line with what the updates widget and the assignments tool have. As well as the the my courses widget options.

Updating lang term to match assignments and update widget

---

package.json

The Phoenix team has released a new major version of `sequences` and we broke CI by bumping it in BSI without bumping it here or in `enrollments`. I double-checked that there were no breaking changes for `organizations` or `enrollments` BUT please feel free to double-check the diff for the `v2.0.1` release commit, or later releases.
https://github.com/BrightspaceHypermediaComponents/sequences/commit/40c2bc481acf70b32007466e7fdf08954284b0be

Bump sequences to major version 2

---

components/d2l-organization-image/d2l-organization-image.js
demo/d2l-organization-image/d2l-organization-image-demo.html

[Rally](https://rally1.rallydev.com/#/357252966636d/custom/367300408400?qdp=%2Fdetail%2Fuserstory%2F384013536908)

d2l-organization-image add a skeleton while loading

---

components/d2l-organization-admin-list/d2l-organization-admin-list.js

context:
BrightspaceUI/core#681
This updates the slot name secondary so supporting-info

Update slot name to supporting-info

---

demo/d2l-organization-admin-list/d2l-organization-admin-list.html
demo/d2l-organization-availability-set/d2l-organization-availability-set.html
demo/d2l-organization-consortium/d2l-organization-consortium.html
demo/d2l-organization-detail-card/d2l-organization-detail-card-demo.html
demo/d2l-organization-image/d2l-organization-image-demo.html
package.json

Not needed anymore! Also because some of these we not `devDependencies`, it was forcing BSI to install them.

removing IE11 polyfills

---

README.md
components/d2l-organization-date/d2l-organization-date.js
components/d2l-organization-info/d2l-organization-info.js
package.json
test/d2l-organization-date/d2l-organization-date.js
test/d2l-organization-info/d2l-organization-info.js

When re-ordering cards in My Courses, DOM nodes are being reused and these values are not being cleared if a card is moving into the place of one that _did_ have a semester or date info, but it _doesn't_.

DE40642 - Clear start date, end date, and semester info accordingly

---

package.json

So that libraries which depend on this one don't need to install it.

fix: make es-dev-server a devDependency

---

.eslintignore

We need the translation PRs for fr-on but they are failing due to eslint errors. 
Updating eslintignore to ignore lang files

Fix: Eslint to ignore lang files

---

components/.github/pull_request_template.md

So I ran across this and figured I'd clean it up (this was added a few weeks before I wrote all the auto-BSI stuff).  But the template doesn't seem to be working at all from my quick test... @AKobets @zinabat have you seen this work or should the whole file just be deleted?  I can't ask Cheick 😢

Remove BSI reminder from PR template
