- components/d2l-organization-updates/d2l-organization-updates.html
Updated margin and padding for updates and changed max-width to 20%
> Added Top padding to be 0

- bower.json
- components/d2l-organization-info/d2l-organization-info.html
- test/d2l-organization-info/d2l-organization-info.js
Moved title to the left.
Using d2l-card meta and title components to format text.
> Text in d2l-organization-info format change

- bower.json
- components/d2l-organization-updates/d2l-organization-updates-behavior.html
- components/d2l-organization-updates/d2l-organization-updates.html
- demo/data/notification.json
- demo/data/presentation/1.json
- demo/data/presentation/2.json
- demo/data/presentation/3.json
- test/d2l-organization-updates/d2l-organization-updates.js
Requires https://github.com/Brightspace/d2l-hm-constants-behavior/pull/71 so update to the required version when it is merged.
> Connect links to the updates.

- OrganizationEntity.js
A way to add which classes this entity can have. So you can do `OrganizationEntity.hasClass(classes.active)`
> Add a const class export constants.

- OrganizationEntity.js
- components/d2l-organization-detail-card/d2l-organization-detail-card.js
- demo/d2l-organization-detail-card/d2l-organization-detail-card-demo.html
- demo/data/organization-current.json
- demo/data/organization-future.json
- demo/index.html
- package.json
- test/d2l-organization-detail-card/d2l-organization-detail-card.html
- test/d2l-organization-detail-card/d2l-organization-detail-card.js
- test/index.html
Basically the detail enrollment card but this one has the entry point from the organization domain and so doesn't have information such as due and completion date.
> Add organization detail card

- package.json
- test/index.html
Add del package
Switch the typography to dependencies
> Clean up tests.

- components/d2l-organization-updates/build/lang/ar.js
- components/d2l-organization-updates/build/lang/de.js
- components/d2l-organization-updates/build/lang/en.js
- components/d2l-organization-updates/build/lang/es.js
- components/d2l-organization-updates/build/lang/fi.js
- components/d2l-organization-updates/build/lang/fr.js
- components/d2l-organization-updates/build/lang/ja.js
- components/d2l-organization-updates/build/lang/ko.js
- components/d2l-organization-updates/build/lang/nl.js
- components/d2l-organization-updates/build/lang/pt.js
- components/d2l-organization-updates/build/lang/sv.js
- components/d2l-organization-updates/build/lang/tr.js
- components/d2l-organization-updates/build/lang/zh-tw.js
- components/d2l-organization-updates/build/lang/zh.js
Please note this change is targeted for `20.19.07` release. So, we do not have to rush to ship the translation in `20.19.06` release.
> Updating lang term value

- components/d2l-organization-consortium/d2l-organization-consortium-tabs.js
- components/d2l-organization-date/d2l-organization-date.js
- components/d2l-organization-detail-card/d2l-organization-detail-card.js
- components/d2l-organization-image/d2l-organization-image.js
- components/d2l-organization-info/d2l-organization-info.js
- components/d2l-organization-name/d2l-organization-name.js
- components/d2l-organization-updates/d2l-organization-updates.js
- package.json
Mostly just moving code around based on the update brightspace config
> bump eslint to latest version

- .travis.yml
- components/d2l-organization-image/d2l-organization-image.js
- demo/d2l-organization-detail-card/d2l-organization-detail-card-demo.html
- demo/d2l-organization-image/d2l-organization-image-demo.html
- demo/data/learningPath/learning-path-sequence-root.json
- demo/data/learningPath/organization-learning-path.json
- demo/data/organization-current.json
- demo/data/organization-future.json
- demo/data/organization-no-dates.json
- demo/data/organization-no-semester.json
- demo/data/organization-past.json
- test/d2l-organization-image/d2l-organization-image.html
- test/d2l-organization-image/d2l-organization-image.js
- test/d2l-organization-image/learning-path-sequence-root.js
This shows 3 images for learning path and one for courses. 
It can support 2 images as well.
There is rtl support.
> Organization image to support learning paths.

- components/d2l-organization-image/d2l-organization-image.js
Noticed when there was two images there was still a border. To fix this put the border on the 3rd image.
> Have border on the top of the 3rd image.

- components/d2l-organization-detail-card/d2l-organization-detail-card.js
> Update colors and padding for text

- components/d2l-organization-availability-set/README.MD
- components/d2l-organization-availability-set/d2l-organization-availability-set.js
- package.json
A shell component to just every things weird up. There will be subsequent user stories to complete this component with a demo page and tests.
> add d2l-organization-availability-set component

- demo/d2l-organization-consortium/d2l-organization-consortium.html
- demo/data/consortium/organization1-consortium.json
- demo/data/consortium/organization2-consortium.json
- demo/data/consortium/organization3-consortium.json
- demo/data/consortium/organization4-consortium.json
You mentioned you were probably going to change the key, so the demo data would need to change again, but I've found this helpful for now
> Add tab switching to demo

- components/d2l-organization-consortium/d2l-organization-consortium-tabs.js
- demo/d2l-organization-consortium/d2l-organization-consortium.html
- demo/data/consortium/organization1-consortium.json
- demo/data/consortium/organization2-consortium.json
- demo/data/consortium/organization3-consortium.json
- demo/data/consortium/organization4-consortium.json
- package.json
- test/d2l-organization-consortium/d2l-organization-consortium-tabs.js
Switching over to use the org homepage url as the key for our state map.  Hopefully that will be unique enough for consortium users.
> DE35507 Duplicate named orgs are unique tabs

- components/d2l-organization-availability-set/d2l-organization-availability-set.js
to address https://github.com/BrightspaceHypermediaComponents/organizations/issues/117
> check that things exist

- components/d2l-organization-consortium/d2l-organization-consortium-tabs.js
- demo/d2l-organization-consortium/d2l-organization-consortium.html
- demo/index.html
Fixes the placement and the border width, based on Jeff's design specs.
> US109896 - Fix notification dot

- components/d2l-organization-consortium/d2l-organization-consortium-tabs.js
- test/d2l-organization-consortium/d2l-organization-consortium-tabs.js
Matching design here: https://d2l.invisionapp.com/share/P3T1Z9TVBK6#/screens/374651845
> US109897 - Add hover and focus effects to the org tabs

- components/d2l-organization-consortium/d2l-organization-consortium-tabs.js
- demo/d2l-organization-consortium/d2l-organization-consortium.html
Everything was working in the demo here with a hardcoded token, but in the LMS we pass in a token getter function that returns promise.  Fixing that and adjusting the demo page to have one of each style.
> DE36611 DE36612 - Fix org tabs cache

- components/d2l-organization-image/d2l-organization-image.js
> Add an image to learning paths without course.

- components/d2l-organization-admin-list/d2l-organization-admin-list-pager.js
- components/d2l-organization-admin-list/d2l-organization-admin-list.js
- components/d2l-organization-admin-list/lang/en.js
- test/d2l-organization-admin-list/d2l-organization-admin-list.js
Loading Skeletons
Paging fixed in edge
Paging buttons no longer overlap
> Polish admin list

- components/d2l-organization-admin-list/d2l-organization-admin-list.js
[rally](https://rally1.rallydev.com/#/357252966636d/custom/367300408400?qdp=%2Fdetail%2Fdefect%2F363021935756)
after fix
> Truncate title

- components/d2l-organization-admin-list/d2l-organization-admin-list-pager.js
- components/d2l-organization-admin-list/d2l-organization-admin-list-search-header.js
- components/d2l-organization-admin-list/d2l-organization-admin-list.js
- components/d2l-organization-admin-list/localization.js
- components/d2l-organization-availability-set/d2l-current-organization-availability.js
- components/d2l-organization-availability-set/d2l-organization-availability-set.js
- components/d2l-organization-availability-set/d2l-organization-availability.js
- components/d2l-organization-availability-set/localization.js
Context:
DE39804 - https://rally1.rallydev.com/#/357252966636d/custom/367300408400?detail=%2Fdefect%2F405047056952
Quality:
Tested with local LMS on MSEdge
> DE39804 fix langterm files for d2l-organization-admin-list

- components/d2l-organization-admin-list/lang/fr-on.js
- components/d2l-organization-admin-list/localization.js
- components/d2l-organization-availability-set/lang/fr-on.js
- components/d2l-organization-availability-set/localization.js
- components/d2l-organization-completion/lang/fr-on.js
- components/d2l-organization-completion/localization.js
- components/d2l-organization-consortium/build/lang/fr-on.js
- components/d2l-organization-consortium/lang/fr-on.json
- components/d2l-organization-consortium/organization-consortium-localize.js
- components/d2l-organization-date/OrganizationDateLocalize.js
- components/d2l-organization-date/build/lang/fr-on.js
- components/d2l-organization-date/lang/fr-on.json
- components/d2l-organization-detail-card/OrganizationDetailCardLocalize.js
- components/d2l-organization-detail-card/build/lang/fr-on.js
- components/d2l-organization-detail-card/lang/fr-on.json
- components/d2l-organization-updates/OrganizationUpdatesLocalize.js
- components/d2l-organization-updates/build/lang/fr-on.js
- components/d2l-organization-updates/lang/fr-on.json
> Fr-on lang pack

- components/d2l-organization-admin-list/lang/fr-on.js
last PR didn't trigger a release version
> fix: release version
